# Generated by Django 3.0.2 on 2020-04-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='pictures/%y/%m/%d/'),
        ),
    ]
