# Generated by Django 3.0.2 on 2020-05-09 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200509_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': []},
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Choice'),
        ),
    ]
